### ISSUE TITLE
CSS Color Module Level 4 compatibility

### ISSUE THREAD

**Issue by mabar** [oddbird/accoutrement-color#8]
In css lvl 4 is specified color() function. So if it will be accepted, color() function in accoutrement-color must be renamed for compatibility with standard. `get-color()` would be nice.

With this change I would also like to throw error when is requested color not listed in configuration. I don't see current behavior as something expected.

color() function draft [here](https://drafts.csswg.org/css-color/#color-function)

**Comment by mirisuzanne** [comment]
Thanks for this!

**Comment by mabar** [comment]
Btw, `color('red')` returns color specified in configuration, but `color(red)` returns `red`. Is it a bug or feature?

**Comment by mirisuzanne** [comment]
Neither a bug nor a feature. :)

That's a combination of Sass types and your accoutrement settings. Sass considers `red` a color, and `"red"` a string. Either one can be used as a key in your color map, and will return the value assigned to it – but they are distinct keys (and the color value can be called directly without setting a key):

```scss
$color: (
  red: green,
  'red': blue,
);
```

In that example, `color(red)` now returns `green`, while `color('red')` returns `blue`. `color(blue)` is not set in our map, but is a valid Sass color, so it would return unchanged. We've done nothing to alter the Sass defaults.

**Comment by ThePeach** [comment]
that always baffled me, thanks for the explanation @mirisuzanne
